import type { SubtitleLanguage } from "@/lib/presentation/types";
import type { Live2DModelBindings } from "@/lib/avatar/live2d-avatar-provider";
import type { Live2DModelLayout } from "@/lib/avatar/model-layout";
import type { VoiceDeliveryMode } from "@/lib/voice/speech-chunks";

export type AgentMode = "hermes";
/** Audio is generated by the server-selected provider from config.json. */
export type VoiceMode = "configured";
export type AvatarMode = "live2d";
const STAGE_BACKGROUNDS = [
  "plain",
  "room",
  "pattern-sparkles",
  "pattern-twinkle",
  "pattern-gingham",
  "pattern-stars",
  "pattern-swirls",
  "custom",
] as const;
export type StageBackground = (typeof STAGE_BACKGROUNDS)[number];

export function isStageBackground(value: unknown): value is StageBackground {
  return typeof value === "string"
    && (STAGE_BACKGROUNDS as readonly string[]).includes(value);
}
export type HostedAvatarModel = {
  id: string;
  name: string;
  url: string;
  addedAt: number;
};

export type KanaPreferences = {
  onboardingCompleted: boolean;
  /** Interface copy language; dictionary lives in lib/ui/copy.ts. */
  uiLocale: "id" | "en";
  subtitleLanguage: SubtitleLanguage;
  agentMode: AgentMode;
  voiceEnabled: boolean;
  voiceMode: VoiceMode;
  avatarMode: AvatarMode;
  stageBackground: StageBackground;
  customBackgroundId?: string;
  hermes: {
    /** Working folder for the managed Hermes process (server-side concern). */
    cwd: string;
  };
  qwen3Tts: {
    baseUrl: string;
    voiceId: string;
    deliveryMode: VoiceDeliveryMode;
  };
  live2d: {
    modelUrl: string;
    modelId?: string;
    modelName?: string;
    coreScriptUrl: string;
    mouthOpenParameter: string;
    bindingProfiles?: Record<string, Live2DModelBindings>;
    layoutProfiles?: Record<string, Live2DModelLayout>;
    hostedModels?: HostedAvatarModel[];
  };
};

export interface PreferencesStore {
  load(): KanaPreferences;
  save(preferences: KanaPreferences): void;
}
